#!/bin/sh

# Copyright ©2021 The tomuvol-cyclone5-module Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

set -e
set -x

GOARCH=arm go build -v -o eda-irq-watch ./main.go
